name: Deploy to server

on:
  push:
    branches: [main]

jobs:
  build:
    # 运行的环境
    runs-on: ubuntu-latest
    # 执行的步骤
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/blog
            sudo git pull origin main
            npm install
            npm run build
